### ISSUE TITLE
Отображать не более 3 строк текста, но текст может быть какой угодно длины

### ISSUE THREAD

**Issue by Glazomer** [avito-tech/vas-frontend-trainee-assignment#3]
Что это значит? Т.е. при случае, когда текст не вмещается в 3 строчки, надо уменьшать размер? Уточните пожалуйста.

**Comment by suprahfly** [comment]
Нет, размер шрифта не меняется. Показывается только тот текст который влезает в 3 строчки

**Comment by Glazomer** [comment]
> Нет, размер шрифта не меняется. Показывается только тот текст который влезает в 3 строчки

Можно запрещать пользователю вводить больше 3ех строчек текста?

**Comment by suprahfly** [comment]
Нет

**Comment by Glazomer** [comment]
Очень странное со стороны UX условие, посколько пользователю будет не понятно куда пропадает текст.
Но ладно...
